export const jobs = [
  {
    id: 'job-201',
    company: 'TechNova Inc.',
    jobTitle: 'Frontend Developer',
    jobPostingURL: 'https://example.com/jobs/201',
    stage: 'Applied',
    appliedDate: '2024-04-01',
    location: 'Remote',
    salaryRange: '$80k - $100k',
    techStack: ['Vue.js', 'Tailwind CSS'],
    notes: 'Referred by John',
  },
  {
    id: 'job-202',
    company: 'DevSolutions',
    jobTitle: 'Backend Engineer',
    jobPostingURL: 'https://example.com/jobs/202',
    stage: 'Applied',
    appliedDate: '2024-03-25',
    location: 'Berlin',
    salaryRange: '€60k - €75k',
    techStack: ['Node.js', 'Express', 'PostgreSQL'],
    notes: 'Waiting for reply',
  },
  {
    id: 'job-203',
    company: 'InnoTech',
    jobTitle: 'Full Stack Developer',
    jobPostingURL: 'https://example.com/jobs/203',
    stage: 'Applied',
    appliedDate: '2024-03-12',
    location: 'London',
    salaryRange: '£65k - £80k',
    techStack: ['Vue.js', 'Laravel'],
    notes: 'Application submitted via referral',
  },
  {
    id: 'job-204',
    company: 'CloudSoft',
    jobTitle: 'DevOps Engineer',
    jobPostingURL: 'https://example.com/jobs/204',
    stage: 'Interview',
    appliedDate: '2024-03-05',
    location: 'New York',
    salaryRange: '$90k - $110k',
    techStack: ['AWS', 'Docker', 'Kubernetes'],
    notes: 'Tech interview scheduled',
  },
  {
    id: 'job-205',
    company: 'Design Studios',
    jobTitle: 'UX Designer',
    jobPostingURL: 'https://example.com/jobs/205',
    stage: 'Interview',
    appliedDate: '2024-03-18',
    location: 'Remote',
    salaryRange: '$70k - $85k',
    techStack: ['Figma', 'Adobe XD'],
    notes: 'Design challenge submitted',
  },
  {
    id: 'job-206',
    company: 'QuantumLeap',
    jobTitle: 'Product Manager',
    jobPostingURL: 'https://example.com/jobs/206',
    stage: 'Offer',
    appliedDate: '2024-02-20',
    location: 'Toronto',
    salaryRange: '$100k - $130k',
    techStack: ['Agile', 'Scrum', 'Jira'],
    notes: 'Offer received and under review',
  },
];
